[package]
name = "keyboard_to_xinput"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inputbot = "0.5.1"
vigem-client = "0.1.4"
